apiVersion: v1
kind: Service
metadata:
  namespace: {{NAMESPACE}}
  name: finance-frontend-dev
spec:
  selector:
    app: finance-frontend-develop
  ports:
    - name: application
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: storybook-app
      protocol: TCP
      port: 3005
      targetPort: 8085
    - name: typedoc-app
      protocol: TCP
      port: 3006
      targetPort: 8086
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{NAMESPACE}}
  name: finance-frontend-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-frontend-develop
  template:
    metadata:
      labels:
        app: finance-frontend-develop
      annotations:
        fluentd.active: 'true'
    spec:
      containers:
        - name: frontend
          image: freenance/frontend-dev:{{IMAGE_TAG}}
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "150m"
          envFrom:
            - secretRef:
                name: finance-dev-front-secret
          ports:
            - containerPort: 3000
        - name: storybook
          image: freenance/storybook-typedoc:{{IMAGE_TAG}}
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "150m"
          ports:
            - containerPort: 8085
        - name: typedoc
          image: freenance/storybook-typedoc:{{IMAGE_TAG}}
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "150m"
          ports:
            - containerPort: 8086
