apiVersion: v1
kind: Service
metadata:
  namespace: {{NAMESPACE}}
  name: finance-frontend-dev
spec:
  selector:
    app: finance-frontend-develop
  ports:
    - name: application
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{NAMESPACE}}
  name: finance-frontend-dev-sb
spec:
  selector:
    app: finance-frontend-dev-sb
  ports:
    - name: application
      protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{NAMESPACE}}
  name: finance-frontend-dev-td
spec:
  selector:
    app: finance-frontend-dev-td
  ports:
    - name: application
      protocol: TCP
      port: 8086
      targetPort: 8086
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{NAMESPACE}}
  name: finance-frontend-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-frontend-develop
  template:
    metadata:
      labels:
        app: finance-frontend-develop
      annotations:
        fluentd.active: 'true'
    spec:
      containers:
        - name: frontend
          image: freenance/frontend-dev:{{IMAGE_TAG}}
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "150m"
          envFrom:
            - secretRef:
                name: finance-dev-front-secret
          ports:
            - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{NAMESPACE}}
  name: finance-frontend-dev-sb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-frontend-develop-sb
  template:
    metadata:
      labels:
        app: finance-frontend-develop-sb
      annotations:
        fluentd.active: 'true'
    spec:
      containers:
        - name: frontend-sb
          image: freenance/frontend-sb:{{IMAGE_TAG}}
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 8085
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{NAMESPACE}}
  name: finance-frontend-dev-td
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-frontend-develop-td
  template:
    metadata:
      labels:
        app: finance-frontend-develop-td
      annotations:
        fluentd.active: 'true'
    spec:
      containers:
        - name: frontend-td
          image: freenance/frontend-td:{{IMAGE_TAG}}
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 8086
